language: go
install:
  - go get code.google.com/p/goprotobuf/proto
  - go get github.com/crhym3/aegot/aet
  - cd $TRAVIS_BUILD_DIR && $HOME/gopath/bin/aet init ./endpoints
script:
  - cd $TRAVIS_BUILD_DIR && $HOME/gopath/bin/aet test -v ./endpoints
